# Generated by Django 2.1.1 on 2018-10-07 10:23

import db.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('url', models.TextField()),
                ('type', models.CharField(choices=[('VID', 'Video'), ('AUD', 'Audio'), ('PIC', 'Picture'), ('DOC', 'Document'), ('XLS', 'Excel'), ('PPT', 'Powerpoint'), ('GFORM', 'Google form'), ('GDOC', 'Google document')], default='DOC', max_length=255)),
            ],
            options={
                'db_table': 'mangalyacore_material_content',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pass_grade', db.models.DecimalRangeField(decimal_places=2, default=50, max_digits=5)),
            ],
            options={
                'db_table': 'mangalyacore_courses',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'mangalyacore_materials',
            },
        ),
        migrations.CreateModel(
            name='UserCourseMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', db.models.DecimalRangeField(decimal_places=2, default=0, max_digits=5)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Material')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mangalyacore_user_course_material',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='material_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Material'),
        ),
    ]
