# Generated by Django 2.1.1 on 2018-10-08 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='material_id',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='usercoursematerial',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='usercoursematerial',
            old_name='material_id',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='usercoursematerial',
            old_name='user_id',
            new_name='user',
        ),
    ]
